name: Meu Primeiro Workflow

# Dispara a automação sempre que houver um "push" na branch main
on:
  push:
    branches: [ main ]

jobs:
  exemplo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Rodar um comando de teste
        run: echo "O GitHub Actions está funcionando com sucesso!"
